-- Labyrinth of the Demon King PL: Polish subtitles under the burned-in English text of
-- the opening lore movie (Movies/OpeningText_*.bk2), shown only when the culture is pl.
-- Own overlay widget above the cutscene; nothing in the game is changed. Lines and
-- times (seconds of the Bink movie) come from subtitles.lua, generated by the build
-- from translations/en-pl-review.json (namespace OpeningText).
local VERSION = "0.4"
local LINES = require("subtitles")
local TAG = "[notgeesePL " .. VERSION .. "] "
local FONT = "/Game/Fonts/EB_Garamond/EBGaramond-VariableFont_wght_Font.EBGaramond-VariableFont_wght_Font"
local PLAYER = "/Game/Movies/BinkMyPlayer.BinkMyPlayer"
local MOVIE = "OpeningText"
local FADE = 0.4

local state = {cut = nil, overlay = nil, text = nil, opening = false, shown = nil, t0 = nil}

local function log(m) print(TAG .. tostring(m) .. "\n") end
local function valid(o) return o ~= nil and o:IsValid() end
local function try(label, f)
    local ok, r = pcall(f)
    if not ok then log(label .. " failed: " .. tostring(r)) return nil end
    return r
end
local function str(v)
    if v == nil then return "" end
    local ok, s = pcall(function() return v:ToString() end)
    return ok and s or tostring(v)
end

-- FTimespan arrives as a table; Ticks are 100 ns.
local function seconds(span)
    local ok, ticks = pcall(function() return span.Ticks end)
    if ok and type(ticks) == "number" then return ticks / 1e7 end
end

local function polish()
    local lib = StaticFindObject("/Script/Engine.Default__KismetInternationalizationLibrary")
    local culture = str(lib:GetCurrentCulture())
    return culture == "pl" or culture:sub(1, 3) == "pl-"
end

local function is_opening(cut)
    local path = try("source", function() return str(cut.CutsceneToPlay.FilePath) end) or ""
    return path:find(MOVIE, 1, true) ~= nil, path
end

local function build(outer)
    local w = StaticConstructObject(StaticFindObject("/Script/UMG.UserWidget"), outer, FName("notgeesePL_Subtitles"))
    local tree = StaticConstructObject(StaticFindObject("/Script/UMG.WidgetTree"), w, FName("notgeesePL_Tree"))
    w.WidgetTree = tree
    local canvas = StaticConstructObject(StaticFindObject("/Script/UMG.CanvasPanel"), tree, FName("notgeesePL_Canvas"))
    tree.RootWidget = canvas
    local tb = StaticConstructObject(StaticFindObject("/Script/UMG.TextBlock"), tree, FName("notgeesePL_Text"))
    local slot = canvas:AddChildToCanvas(tb)
    slot:SetAnchors({Minimum = {X = 0.5, Y = 1.0}, Maximum = {X = 0.5, Y = 1.0}})
    slot:SetAlignment({X = 0.5, Y = 1.0})
    slot:SetPosition({X = 0.0, Y = -48.0})
    slot:SetAutoSize(true)
    local font = StaticFindObject(FONT)
    if not valid(font) then font = try("font", function() return LoadAsset(FONT) end) end
    if valid(font) then tb:SetFont({FontObject = font, TypefaceFontName = FName("Default"), Size = 26}) end
    tb.WrapTextAt = 1250.0
    tb:SetJustification(1)
    tb:SetColorAndOpacity({SpecifiedColor = {R = 0.86, G = 0.85, B = 0.82, A = 1.0}, ColorUseRule = 0})
    tb:SetShadowOffset({X = 1.5, Y = 1.5})
    tb:SetShadowColorAndOpacity({R = 0.0, G = 0.0, B = 0.0, A = 0.85})
    tb:SetRenderOpacity(0.0)
    w:AddToViewport(1000)
    return w, tb
end

local function reset()
    if valid(state.overlay) then try("remove", function() state.overlay:RemoveFromParent() end) end
    state.cut, state.overlay, state.text, state.opening, state.shown, state.t0 = nil, nil, nil, false, nil, nil
end

local function tick()
    local cut = FindFirstOf("UI_PrerenderedCutscene_C")
    if not valid(cut) then
        if state.cut then reset() end
        return
    end
    local player = StaticFindObject(PLAYER)
    if not valid(player) then return end
    if state.cut ~= cut:GetAddress() then
        reset()
        state.cut = cut:GetAddress()
        local opening, path = is_opening(cut)
        state.opening = opening and polish()
        if state.opening then
            local ok, w, tb = pcall(build, cut:GetOuter())
            if ok then state.overlay, state.text = w, tb; log("subtitles for " .. path)
            else log("overlay failed: " .. tostring(w)); state.opening = false end
        end
    end
    if not state.opening or not valid(state.text) then return end
    -- Player time keeps the lines in sync; wall clock is only a fallback.
    local t = seconds(try("time", function() return player:GetTime() end))
    if t == nil then
        if not state.t0 and player:IsPlaying() then state.t0 = os.clock() end
        t = state.t0 and (os.clock() - state.t0) or 0
    end
    local line, alpha = nil, 0.0
    for i, l in ipairs(LINES) do
        if t >= l[1] and t <= l[2] then
            line = i
            alpha = math.min(1.0, (t - l[1]) / FADE, (l[2] - t) / FADE)
            break
        end
    end
    if line and line ~= state.shown then state.text:SetText(FText(LINES[line][3])) end
    state.shown = line
    state.text:SetRenderOpacity(math.max(0.0, alpha))
end

log("loaded, " .. #LINES .. " subtitle lines")
LoopAsync(50, function()
    ExecuteInGameThread(function() try("tick", tick) end)
    return false
end)
