"""Dump the English source text and refresh the review file.

Reads the game's own en/Game.locres and refreshes translations/en-pl-review.json,
the only translation file: one row per entry, English beside the
Polish already in the file (empty = not translated yet), in the resource's own order.

Keys are 32-character hashes generated by the engine, so the namespace is what
gives a row its context - UIStringTable is the menu, Dialogue_Subs the subtitles,
CODEX the readable entries, and so on.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import locres

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parents[1] / 'tools'))

from translations import polish_by_ref, review_path, write_entries  # noqa: E402


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / 'translations/en.locres',
                        help='The game\'s own en/Game.locres, extracted from the pak')
    args = parser.parse_args()

    english = locres.load(args.source)
    polish = polish_by_ref(ROOT) if review_path(ROOT).exists() else {}

    rows, translated = [], 0
    for namespace, entry in english.entries():
        text = polish.get((namespace, entry.key), '')
        rows.append({'namespace': namespace, 'key': entry.key, 'english': entry.text, 'polish': text})
        translated += bool(text)

    write_entries(ROOT, rows)
    out = review_path(ROOT)

    by_namespace = {}
    for row in rows:
        counts = by_namespace.setdefault(row['namespace'] or '(none)', [0, 0])
        counts[0] += 1
        counts[1] += bool(row['polish'])
    print(json.dumps({'entries': len(rows), 'translated': translated,
                      'english_characters': sum(len(r['english']) for r in rows),
                      'namespaces': {k: f'{v[1]}/{v[0]}' for k, v in by_namespace.items()},
                      'output': str(out)}, ensure_ascii=False))


if __name__ == '__main__':
    main()
