"""Generate translations/structure.yaml for the review workspace from the I2 term names.

Groups by I2 category; sequences for cutscenes and projector memories (real conversations),
lines ordered by the number in the term, speaker from the term suffix.
"""
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parents[1] / 'tools'))
from translations import load_entries  # noqa: E402

GROUPS = [
    ('interfejs', 'Menu, ustawienia, HUD i teksty z kodu'),
    ('rozdzialy', 'Tytuły rozdziałów i ekrany wyjścia'),
    ('przerywniki', 'Przerywniki'),
    ('poziomy', 'Kwestie Jamesa na poziomach i samouczek'),
    ('okrzyki', 'Okrzyki Jamesa i Draculae'),
    ('zakladnicy', 'Zakładnicy'),
    ('projektory', 'Projektory: wspomnienia Jamesa i Janet'),
    ('radio', 'Radio, telefony i komunikaty'),
    ('luis', 'Luis (prolog El Paso, Nightmare)'),
    ('tworcy', 'Napisy końcowe'),
]
RULES = [
    ('tworcy', 'i2', r'Credits'),
    ('rozdzialy', 'i2', r'^(EPE Chapters/|Chapter Title|EPE Quit Messages/)'),
    ('przerywniki', 'i2', r'^EPE Cutscene Subtitles/'),
    ('poziomy', 'i2', r'^(EPE Level Subtitles/|Subtitles - )'),
    ('zakladnicy', 'i2', r'^EPE Ambient Subtitles/Hostage_'),
    ('okrzyki', 'i2', r'^EPE Ambient Subtitles/'),
    ('projektory', 'i2', r'^EPE Optional Subtitles/Projector_'),
    ('radio', 'i2', r'^EPE Optional Subtitles/'),
    ('luis', 'i2', r'^VOSub_Luis'),
    ('interfejs', 'i2', r'^(Main Menu|Interaction|Key Message|Weapon Name|Ticker Message)'),
    ('tworcy', 'ui', r'DIRECTOR'),
    ('interfejs', 'ui', r'.'),
    ('przerywniki', 'subtitle', r'.'),
    ('interfejs', 'code', r'.'),
    ('interfejs', 'pattern', r'.'),
]
SPEAKERS = {'James': 'james', 'Draculae': 'draculae', 'Dracule': 'draculae', 'Elevator': 'elevator', 'Pharaoh': 'pharaoh'}
# Old-named cutscenes still referenced by Timeline clips (technical.md); other old names are unused copies.
LIVE_OLD = {'Impossible', 'Die_Good', 'Forces_Beyond', 'Reasonable', 'Bathroom_Werewolf'}


def number(key):
    m = re.search(r' - (\d+)', key) or re.search(r' -(\d+) ', key)
    return int(m.group(1)) if m else 0


def main():
    entries = load_entries(ROOT)
    scenes = {}
    for e in entries:
        if e.get('namespace') != 'i2':
            continue
        m = re.match(r'^EPE (Cutscene|Optional) Subtitles/([^ ]+) -', e['key'])
        if not m:
            continue
        kind, scene = m.groups()
        if kind == 'Optional' and not scene.startswith('Projector_'):
            continue
        if kind == 'Cutscene' and not (re.match(r'^\d\d_', scene) or scene in LIVE_OLD):
            continue
        scenes.setdefault((kind, scene), []).append(e['key'])
    sequences = []
    for (kind, scene), keys in sorted(scenes.items(), key=lambda kv: (kv[0][0], kv[0][1])):
        if len(keys) < 2:
            continue
        lines = []
        for key in sorted(keys, key=number):
            line = {'key': key, 'namespace': 'i2'}
            suffix = key.rsplit(' - ', 1)[-1] if ' - ' in key else ''
            if suffix in SPEAKERS:
                line['speaker'] = SPEAKERS[suffix]
            lines.append(line)
        name = re.sub(r'^Projector_', '', scene)
        name = re.sub(r'_\d+$', '', name) if kind == 'Optional' else name
        sequences.append({
            'id': re.sub(r'[^a-z0-9-]', '-', scene.lower()),
            'name': ('Przerywnik ' if kind == 'Cutscene' else 'Projektor ') + name.replace('_', ' '),
            'group': 'przerywniki' if kind == 'Cutscene' else 'projektory',
            'order': {'certainty': 'certain', 'source': 'numeracja w nazwie terminu I2'},
            'speakers': {'certainty': 'certain', 'source': 'nazwa mówcy w terminie I2'},
            'lines': lines,
        })
    data = {
        'format': 1,
        'groups': [{'id': i, 'name': n} for i, n in GROUPS],
        'rules': [{'group': g, 'namespace': ns, 'match': m} for g, ns, m in RULES],
        'sequences': sequences,
    }
    header = ('# El Paso, Elsewhere: groups and sequences for the review workspace (docs/workspace.md).\n'
              '# Generated by tools/structure.py from I2 term names; edit the script, not this file.\n\n')
    out = ROOT / 'translations/structure.yaml'
    out.write_text(header + yaml.safe_dump(data, allow_unicode=True, sort_keys=False, width=200), encoding='utf-8')
    print(f'groups {len(GROUPS)}, sequences {len(sequences)}')


if __name__ == '__main__':
    main()
