"""Write translations/structure.yaml: Anger Foot groups and conversations for the workspace.

    .venv\\Scripts\\python.exe games\\anger-foot\\tools\\structure.py

A dialogue key is `Dialogue/<area>/<scene> <n> [<speaker> > <addressee>]` (tools/review.py),
so every scene is a conversation: order from the number, speaker from the key. SPEAKERS maps
speakers to bible.yaml characters; nameless NPCs go to npc-m / npc-f by gender in the key;
voices without a bible character (computer, intercom, animals) stay without a speaker.
Run after dialogue keys change.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parents[1] / 'tools'))

from translations import load_entries  # noqa: E402

HEADER = '''# Anger Foot: groups and conversations for the review workspace. Generated by tools/structure.py,
# do not edit by hand. Format: docs/workspace.md.
'''

GROUPS = [
    ('menu', 'Menu i ustawienia', r'^UI/(Main Menu|Pause Menu|Settings Menu|Game Settings|Input Mapping Dialog|Resolution Confirmation Dialog)/'),
    ('levels', 'Poziomy, mapa i cele', r'^UI/(Level Names|World Map|Challenge Levels|Level Goal Types|Star Goals|Level Complete Screen|Boss Defeated Screen)/'),
    ('shoes', 'Buty i znajdźki', r'^UI/(Shoes|Shoe Collection|Collectibles|Collectible Types)/'),
    ('tutorial', 'Samouczki, podpowiedzi i HUD', r'^UI/(Tutorials|Hints|HUD)/'),
    ('story', 'Intro, postacie i telewizja', r'^UI/(Intro Cinematic|Character Names|TV Channel Text)/'),
    ('achievements', 'Osiągnięcia', r'^UI/Achievements/'),
    ('credits', 'Napisy końcowe', r'^UI/Credits/'),
    ('ui-other', 'Interfejs — pozostałe', r'^UI/'),
    ('apartments', 'Dialogi — Apartamentowce', r'^Dialogue/Apartments/'),
    ('sewers', 'Dialogi — Kanały', r'^Dialogue/Sewers/'),
    ('offices', 'Dialogi — Biurowce', r'^Dialogue/Offices/'),
    ('dungeons', 'Dialogi — Lochy', r'^Dialogue/Dungeons/'),
    ('crime-tower', 'Dialogi — Wieża Zbrodni', r'^Dialogue/Crime Tower/'),
]

SPEAKERS = {
    'Anger Girl (Female)': 'anger-girl',
    'Crime Minister (Male)': 'minister',
    'Office Boss (Female)': 'ceo',
    'Pizza Pig (Male)': 'pizza-pig',
    'Goo Cop (Male)': 'goo-cop',
    'Trash Boss (Neutral)': 'trash-boss',
    'Trash Boss Brain (Neutral)': 'trash-boss',
    'Pizza Delivery Guy (Male)': 'npc-m',
}
LINE = re.compile(r'^(Dialogue/[^/]+/.+?) (\d+) \[(.+?) > (.+?)\]$')


def speaker(name: str) -> str | None:
    if name in SPEAKERS:
        return SPEAKERS[name]
    if re.fullmatch(r'NPC( \d+)? \(Male\)', name):
        return 'npc-m'
    if re.fullmatch(r'NPC( \d+)? \(Female\)', name):
        return 'npc-f'
    return None


def main() -> int:
    bible = yaml.safe_load((ROOT / 'translations/bible.yaml').read_text(encoding='utf-8'))
    known = {p['id'] for p in bible['characters']}
    assert set(SPEAKERS.values()) <= known, set(SPEAKERS.values()) - known
    scenes: dict[str, list[tuple[int, str, str]]] = {}
    for e in load_entries(ROOT):
        m = LINE.match(e['key'])
        if m:
            scenes.setdefault(m.group(1), []).append((int(m.group(2)), e['key'], m.group(3)))
    sequences = []
    for scene, lines in scenes.items():
        numbers = sorted(n for n, _, _ in lines)
        if len(lines) < 2 or numbers != list(range(numbers[0], numbers[0] + len(numbers))):
            continue
        group = next((g for g, _, p in GROUPS if re.search(p, scene + '/')), None)
        if group is None:
            continue  # new area: add a group to GROUPS first
        out = []
        for _, key, name in sorted(lines):
            who = speaker(name)
            out.append({'key': key, **({'speaker': who} if who else {})})
        sequences.append({
            'id': re.sub(r'[^a-z0-9]+', '-', scene.split('/', 2)[2].lower()).strip('-'),
            'name': scene.split('/', 2)[2], 'group': group,
            'order': {'certainty': 'certain', 'source': 'numer kwestii w kluczu'},
            'speakers': {'certainty': 'certain', 'source': 'mówiący w kluczu [mówiący > adresat]; NPC po płci (npc-m, npc-f)'},
            'lines': out,
        })
    data = {
        'format': 1,
        'groups': [{'id': g, 'name': n} for g, n, _ in GROUPS],
        'rules': [{'group': g, 'match': p} for g, _, p in GROUPS],
        'sequences': sequences,
    }
    text = HEADER + '\n' + yaml.safe_dump(data, allow_unicode=True, sort_keys=False, width=140)
    (ROOT / 'translations/structure.yaml').write_text(text, encoding='utf-8', newline='\n')
    print(f'{len(GROUPS)} groups, {len(sequences)} conversations, {sum(len(s["lines"]) for s in sequences)} lines in conversations')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
