"""Build a localization-only PAK + minimal selector IoStore overlay, the intro subtitle
mod (UE4SS + Lua) and the release ZIP.

Reads local files to obtain engine keys/selector structure, never changes them.
No game checksum is used as a version gate. Unsupported serialization is rejected
at build time. Actual mounting/rendering must be tested by the user.
Entries with namespace OpeningText are subtitles for the burned-in text of the
opening movie (context: movie and seconds); namespace Hardcoded holds culture-invariant
texts typed into widgets (key `<Widget>/<id>`). Neither is a locres key; both go to Lua.
"""
import argparse
from collections import Counter
import hashlib
import json
import sys
import re
import tempfile
import zipfile
from pathlib import Path
import yaml
from game_pak import GamePak
from iostore import Store,write_overlay
from language_slot import PATH,patch
import locres
import pak

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parents[1] / 'tools'))

from translations import load_entries  # noqa: E402
VERSION='0.5'
STEM='pakchunk99-notgeesePL_P'
PAKS='Shinigami/Content/Paks'
PL_PATH='Shinigami/Content/Localization/Game/pl/Game.locres'
EN_PATH='Shinigami/Content/Localization/Game/en/Game.locres'
TOKENS=re.compile(r'\{[^{}]+\}|</>|<[A-Za-z_][^>]*>')
SUBTITLES='OpeningText'
HARDCODED='Hardcoded'
CUE=re.compile(r'^Movies/OpeningText_001\.bk2 (\d+\.\d)-(\d+\.\d) s$')
BIN='Shinigami/Binaries/Win64/'
MOD=BIN+'ue4ss/Mods/notgeesePL/Scripts/'
RUNTIME=ROOT.parent/'holy-shoot/work/ue4ss/UE4SS_v3.0.1-1140-gf58e8f84.zip'
RUNTIME_SHA256='b954f036b10e9abb0c0c41599311ab1accc53e30515aeed7e48ee22c5b3b1280'
RUNTIME_FILES=('dwmapi.dll','ue4ss/UE4SS.dll','ue4ss/LICENSE','ue4ss/UE4SS-settings.ini')

def lua_string(text):
    assert '\r' not in text and '\0' not in text
    return '"'+text.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')+'"'

def subtitles_lua(entries):
    """Generated Lua table {start, end, text}; cues from `context`, in file order."""
    rows=[];last=-1.0
    for e in entries:
        start,end=map(float,CUE.fullmatch(e['context']).groups())
        assert last<=start<end, e['key'];last=end
        rows.append(f'    {{{start:.1f}, {end:.1f}, {lua_string(e["polish"])}}},')
    return ('-- Generated by tools/build.py from translations/en-pl-review.json (namespace OpeningText).\n'
            'return {\n'+'\n'.join(rows)+'\n}\n').encode('utf-8')

def texts_lua(entries):
    """Generated Lua map widget class -> {English: Polish}."""
    widgets={}
    for e in entries:
        widget=e['key'].split('/')[0]
        assert re.fullmatch(r'(?:UI|BP)_\w+',widget), e['key']
        widgets.setdefault(widget+'_C',{})[e['english']]=e['polish']
    rows=[]
    for widget,pairs in widgets.items():
        rows.append(f'    [{lua_string(widget)}] = {{')
        rows+= [f'        [{lua_string(en)}] = {lua_string(pl)},' for en,pl in pairs.items()]
        rows.append('    },')
    return ('-- Generated by tools/build.py from translations/en-pl-review.json (namespace Hardcoded).\n'
            'return {\n'+'\n'.join(rows)+'\n}\n').encode('utf-8')

def mod_payload(runtime, entries, hardcoded):
    """UE4SS loader, its settings and MIT license (no other mods) plus our two scripts."""
    data=Path(runtime).read_bytes()
    assert hashlib.sha256(data).hexdigest()==RUNTIME_SHA256, 'Unexpected third-party runtime'
    files={}
    with zipfile.ZipFile(runtime) as z:
        for member in RUNTIME_FILES:files[BIN+member]=z.read(member)
    files[BIN+'ue4ss/Mods/mods.txt']=b'notgeesePL : 1\n'
    files[BIN+'ue4ss/Mods/mods.json']=b'[{"mod_name":"notgeesePL","mod_enabled":true}]\n'
    files[MOD+'main.lua']=(ROOT/'plugin/main.lua').read_bytes()
    files[MOD+'subtitles.lua']=subtitles_lua(entries)
    files[MOD+'texts.lua']=texts_lua(hardcoded)
    return files

def validate_payload(stage, polish, expected_widget, mod):
    """Allowlist inside both archive types; reject even a single unrelated chunk or file."""
    base=stage/PAKS/STEM
    expected={f'{PAKS}/{STEM}{ext}' for ext in ('.pak','.utoc','.ucas')}|{'READ-ME.txt'}|set(mod)
    actual={p.relative_to(stage).as_posix() for p in stage.rglob('*') if p.is_file()}
    if actual!=expected:raise ValueError(f'Unexpected payload: {actual ^ expected}')
    for path,body in mod.items():
        if (stage/path).read_bytes()!=body:raise ValueError(f'Unexpected mod file: {path}')
    mount,files=pak.read(base.with_suffix('.pak').read_bytes())
    if mount!='../../../' or set(files)!={PL_PATH}:raise ValueError('PAK must contain Polish text only')
    if files[PL_PATH]!=polish:raise ValueError('Unexpected localization data')
    store=Store(base)
    if set(store.paths)!={PATH} or len(store.ids)!=2:raise ValueError('IoStore must contain only language slot and its header')
    widget=store.read(store.paths[PATH])
    if widget!=expected_widget or len(widget)>26000:raise ValueError('Unexpected/oversized selector carrier')
    for i,chunk in enumerate(store.ids):
        if chunk[11] not in (2,10):raise ValueError('Forbidden chunk type')
        if chunk[11]==10 and len(store.read(i))>1024:raise ValueError('Oversized carrier header')
    if len(widget)>=len(polish):raise ValueError('Selector carrier is not smaller than translation')
    if any(Path(p).suffix in ('.uasset','.uexp','.ubulk','.bk2','.ufont','.exe') for p in actual):raise ValueError('Game asset in payload')
    return expected

def split(review):
    locres_entries=[x for x in review if not x.get('namespace')]
    subtitles=[x for x in review if x.get('namespace')==SUBTITLES]
    hardcoded=[x for x in review if x.get('namespace')==HARDCODED]
    assert len(locres_entries)+len(subtitles)+len(hardcoded)==len(review), 'Unknown namespace'
    return locres_entries,subtitles,hardcoded

def main():
    if not __debug__:raise RuntimeError('Do not disable build validations with -O')
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--game',required=True,type=Path)
    ap.add_argument('--runtime',type=Path,default=RUNTIME)
    args=ap.parse_args()
    game=args.game.resolve();dist=ROOT/'dist';dist.mkdir(exist_ok=True)
    review=load_entries(ROOT)
    assert all(x['polish'] for x in review), 'Full release requires all reviewed entries translated'
    entries,subtitles,hardcoded=split(review)
    assert len({x['key'] for x in entries})==len(entries) and subtitles
    polish={x['key']:x['polish'] for x in entries}
    mod=mod_payload(args.runtime,subtitles,hardcoded)
    source=GamePak(game/PAKS/'pakchunk0-WindowsNoEditor.pak')
    en=source.extract(EN_PATH)
    with tempfile.TemporaryDirectory(prefix='labyrinth-pl-') as tmp:
        tmp=Path(tmp);enfile=tmp/'en.locres';enfile.write_bytes(en)
        english=locres.load(enfile);assert locres.dump(english)==en
        native={e.key:e.text for _,e in english.entries()}
        assert polish and polish.keys()<=native.keys()
        for item in entries:
            text=polish[item['key']];original=native[item['key']]
            assert original==item['english'], f'Source changed: {item["key"]}'
            assert Counter(TOKENS.findall(original))==Counter(TOKENS.findall(text)),item['key']
            assert original.count('\r\n')==text.count('\r\n'),f'Line breaks: {item["key"]}'
        pl=locres.dump(locres.translate(english,{('',key):text for key,text in polish.items()}))
        plfile=tmp/'pl.locres';plfile.write_bytes(pl)
        assert locres.load(plfile).texts()=={('',key):text for key,text in polish.items()}
        original_store=Store(game/PAKS/'pakchunk0-WindowsNoEditor')
        widget,selector=patch(original_store.read(original_store.paths[PATH]))
        stage=tmp/'stage';base=stage/PAKS/STEM
        io=write_overlay(original_store,{PATH:widget},base)
        base.with_suffix('.pak').write_bytes(pak.write({PL_PATH:pl}))
        (stage/'READ-ME.txt').write_bytes((ROOT/'docs/INSTALL.txt').read_bytes())
        for path,body in mod.items():
            (stage/path).parent.mkdir(parents=True,exist_ok=True);(stage/path).write_bytes(body)
        expected=validate_payload(stage,pl,widget,mod)
        output=dist/f'Labyrinth-of-the-Demon-King-PL-{VERSION}.zip'
        candidate=tmp/'candidate.zip'
        with zipfile.ZipFile(candidate,'w',zipfile.ZIP_DEFLATED) as z:
            for path in sorted(expected):z.write(stage/path,path)
        with zipfile.ZipFile(candidate) as z:
            assert set(z.namelist())==expected and z.testzip() is None
            checked=tmp/'checked';z.extractall(checked)
        validate_payload(checked,pl,widget,mod)
        output.write_bytes(candidate.read_bytes())
        report={'version':VERSION,'translated':len(polish),'total':len(native),'subtitles':len(subtitles),'hardcoded':len(hardcoded),
                'locres_bytes':len(pl),'selector':selector,'iostore':io,
                'runtime':'UE4SS v3.0.1-1140-gf58e8f84 (MIT)',
                'package':str(output),'package_bytes':output.stat().st_size,
                'package_sha256':hashlib.sha256(output.read_bytes()).hexdigest(),
                'file_tests':'passed','game_test':'vertical and intro subtitles confirmed by user; hardcoded texts and full campaign not tested'}
        (dist/'build-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
        print(json.dumps({k:v for k,v in report.items() if k not in ('selector','iostore')},ensure_ascii=True))

if __name__=='__main__':main()
